"""add chunk strategy column

Revision ID: be43382f1863
Revises: 57298b279acc
Create Date: 2026-08-02 20:56:04.103219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be43382f1863'
down_revision: Union[str, Sequence[str], None] = '57298b279acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('FIXED', 'SEMANTIC', name='chunkstrategy').create(op.get_bind())
    op.add_column('document_chunk', sa.Column('chunk_strategy', postgresql.ENUM('FIXED', 'SEMANTIC', name='chunkstrategy', create_type=False), server_default='FIXED', nullable=False))
    op.sync_enum_values(
        enum_schema='public',
        enum_name='extractionstatus',
        new_values=['PENDING', 'IN_PROGRESS', 'COMPLETED', 'INDEXED', 'FAILED'],
        affected_columns=[TableReference(table_schema='public', table_name='extraction', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='extractionstatus',
        new_values=['PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'INDEXED'],
        affected_columns=[TableReference(table_schema='public', table_name='extraction', column_name='status')],
        enum_values_to_rename=[],
    )
    op.drop_column('document_chunk', 'chunk_strategy')
    sa.Enum('FIXED', 'SEMANTIC', name='chunkstrategy').drop(op.get_bind())
    # ### end Alembic commands ###
